### ISSUE TITLE
Move back to chef org and/or add me as contributor?

### ISSUE THREAD

**Issue by lamont-granquist** [chef-cookbooks/locale#19]
This hasn't gotten any commits for over 1.5 years now, and has outstanding RHEL7 bugs.

Can we move this back into the chef-cookbooks org?  We can keep everyone on HeavyWater as contributors if you give me a list of users.

Tagging @luckymike

**Comment by luckymike** [comment]
To my knowledge, this was never a Chef cookbook. We're open to handing it over, as it's clearly not been a priority of ours recently.

I've added you as a collaborator so you can begin work immediately. :)

**Comment by lamont-granquist** [comment]
Yeah, actually I think you're right it was never ours, but it is a generic named cookbook that hasn't been getting much love...

Do you care about transferring ownership?  I'd kind of like to transfer it to chef-cookbooks, and then call in an airstrike from tas50 to do his OCD magic on it and update all the nitpicky details...

**Comment by luckymike** [comment]
@lamont-granquist seems we can do this. Maybe email me out of band to coordinate?

**Comment by luckymike** [comment]
SUCCESS \o/
