### ISSUE TITLE
FATAL: NoMethodError: undefined method `[]' for nil:NilClass when locale attribute not defined in the node.

### ISSUE THREAD

**Issue by cadalso** [chef-cookbooks/locale#5]
Hi, 
Running your locale recipe I got this error (full output in the end)

<pre>
[2013-05-23T05:52:37-04:00] FATAL: NoMethodError: undefined method `[]' for nil:NilClass
</pre>

I worked it out declaring the locale in the node attributes

<pre>
{
...
    "locale": {
                "lang" : "en_US.utf8"
        },
...
}
</pre>

It worked that way but I am not sure why because the default attribute in the recipe is the same "en_US.utf8". I am including the recipe in my bp-debian-packages recipe, like

<pre>
# Shell Dependencies
package "emacs"
package "dnsutils"
package "lynx"
package "sudo"
package "mutt"
package "screen"
package "tree"
package "build-essential"

#Postgres Dependencies
include_recipe "locale"
package "postgresql"
package "postgresql-client"
gem_package "pg"

</pre>

Maybe there is some untested dependency on that attribute?

Thanks 

==================================================
Full output when it failed.
<pre>
================================================================================
Recipe Compile Error in /tmp/chef-solo/site-cookbooks/bp-debian-packages/recipes/default.rb
================================================================================

NoMethodError
-------------
undefined method `[]' for nil:NilClass

Cookbook Trace:
---------------
  /tmp/chef-solo/cookbooks/locale/recipes/default.rb:27:in `block in from_file'
  /tmp/chef-solo/cookbooks/locale/recipes/default.rb:26:in `from_file'
  /tmp/chef-solo/site-cookbooks/bp-debian-packages/recipes/default.rb:33:in `from_file'

Relevant File Content:
----------------------
/tmp/chef-solo/cookbooks/locale/recipes/default.rb:

 20:  if platform?("ubuntu", "debian")
 21:
 22:    package "locales" do
 23:      action :install
 24:    end
 25:
 26:    execute "Update locale" do
 27>>     command "update-locale LANG=#{node[:locale][:lang]}"
 28:    end
 29:
 30:  end
 31:
 32:  if platform?("redhat", "centos", "fedora")
 33:
 34:    execute "Update locale" do
 35:      command "locale -a | grep ^#{node[:locale][:lang]}$ && sed -i 's|LANG=.*|LANG=#{node[:locale][:lang]}|' /etc/sysconfig/i18n"
 36:    end

[2013-05-23T05:52:37-04:00] ERROR: Running exception handlers
[2013-05-23T05:52:37-04:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated
[2013-05-23T05:52:37-04:00] FATAL: Stacktrace dumped to /tmp/chef-solo/chef-stacktrace.out
[2013-05-23T05:52:37-04:00] FATAL: NoMethodError: undefined method `[]' for nil:NilClass
ERROR: RuntimeError: chef-solo failed. See output above.

</pre>

**Comment by lamont-granquist** [comment]
chef-solo 12.x (and chef-zolo in 13.x) will also complain about the lack of a depends line now
